# Generated by Django 4.1.7 on 2023-05-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style_type', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='name',
            field=models.CharField(default='asdfasdf', max_length=34, verbose_name='Название'),
        ),
    ]
