# Generated by Django 4.1.7 on 2023-06-02 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('style_type', '0002_outfit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='name',
            field=models.CharField(default='Default Thing', max_length=34, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='thing',
            name='photo',
            field=models.ImageField(default='', upload_to='things/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outfit',
            name='name',
            field=models.CharField(default='Default Outfit', max_length=34, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='outfit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='style_type.outfit', verbose_name='Аутфит'),
        ),
    ]
