# Generated by Django 4.1.6 on 2023-06-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style_type', '0004_alter_category_photo_alter_outfit_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='photo',
            field=models.ImageField(upload_to='static/', verbose_name='Изображение'),
        ),
    ]
