# Generated by Django 4.1.7 on 2023-06-08 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('style_type', '0012_alter_category_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='photo',
        ),
    ]
