# Generated by Django 4.1.6 on 2023-06-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style_type', '0019_alter_category_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='categories_of_outfits/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='photo',
            field=models.ImageField(upload_to='outfits/', verbose_name='Изображение'),
        ),
    ]
