# Generated by Django 4.1.7 on 2023-06-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style_type', '0020_alter_category_photo_alter_outfit_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Default Category', max_length=150, verbose_name='Outfit'),
        ),
    ]
